import = [
   "~/.config/alacritty/themes/rose-pine.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
opacity = 0.999
decorations = "Buttonless"

[font]

#normal.family = "Caskaydia Mono NF"
#normal.style = "light"

#laptop
size = 11
#regular
#size = 20
#for video
# size = 35.0

[shell]
program = "/bin/zsh"
args = ["-c", "tmux new-session -A -s main"]

