import = [
   "~/.config/alacritty/themes/rose-pine.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
opacity = 0.925

decorations = "Buttonless"

[font]
normal.family = "Cascadia Code NF"

#regular
size = 20

#for video
# size = 35.0

